### ISSUE TITLE
Deep object validation?

### ISSUE THREAD

**Issue by hongkongkiwi** [mvhenten/validate-arguments-js#1]
I'm using this validation library, I love it because it's simple and easy to read.

A question I've come up against though... Does this support objects with properties? For example what I'm interested in doing is:

``` javascript
var args = Validate.validateObject({'robot': robot}, 
    'robot': {
        isa: 'object'
    },
    'robot': {
        'uuid': {
            isa: 'string'
        }
    }
});
```

As a temporary solution I'm using a workaround which is kind of ugly and hardly ideal.

``` javascript
var args = Validate.validateObject({'robot': robot, 'robot.uuid': robot.uuid}, {
    'robot': {
        isa: 'object'
    },
    'robot.uuid': {
        isa: 'string'
    }
});
```

**Comment by mvhenten** [comment]
Hi,

Definately a feature nice to have, but not implemented yet.
Maybe the following workaround could work for you?

```
    var Thing = function(){}, thing = new Thing();

    var validated = Validate.validateObject({ thing: thing },
        { thing: { isa: Thing }    
    });

    assert.equal( validated.isValid(), true );
```

If such a feature should be implemented, what would be the right syntax?

```
    var validated = Validate.validateObject({ thing: thing },
        {
            thing: {
                isa: Validate.DuckType(function(value){
                    return _.isString( value.uuid );
            })
        }    
    });

    var validated = Validate.validateObject({ thing: thing },
        { thing: { isa: Object, has: 'uuid', can: 'doSomething' }    
    });
```

**Comment by hongkongkiwi** [comment]
``` javascript
    var Thing = function(){}, thing = new Thing();

    var validated = Validate.validateObject({ thing: thing },
        { thing: { isa: Thing }    
    });

    assert.equal( validated.isValid(), true );
```

This example above doesn't quite work because in my example I need to check JSON objects, so I check that it's a plainObject first and then I need to ensure that some fields I'm expecting are inside the object and typecheck on those fields.

In terms of ideal implementation I think sticking with the simplicity is good and using the current syntax. In following your example, I would add two new things, has and optionally has, this can support immense complexity without actually adding much to the code. Everytime a has is encountered it simply goes one level deeper. See the following example.

``` javascript
var thing = {
    uuid: '1234567ABC',
    doSomething: function() {}
};

var anotherThing = 'Hi Im a thing!';

var manyThings = {
    innerThing: {
        uuid: '20385FBF', // this is optional
        someFunc: function() {}  // this is optional
    },
        thing: thing // this is optional
}

var validated = Validate.validateObject({ thing: thing, anotherThing: anotherThing, manyThings: manyThings }, {
    thing:  { 
        isa: Object, 
        has: {
            uuid: {
                isa: 'string'
            },
            doSomething: {
                isa: 'function'
            }
        }
    },
    anotherThing:  { 
        isa: 'string', 
        optional: true
    },
    manyThings:  { 
        isa: Object, 
        has: {
            innerThing: {
                isa: Object,
                optionallyHas: {
                    uuid: {
                        isa: 'string'
                    },
                    someFunc: {
                        isa: 'function'
                    }
                }
            }
        },
        optionallyHas: {
            thing:  { 
                isa: Object, 
                has: {
                    uuid: {
                        isa: 'string'
                    },
                    doSomething: {
                        isa: 'function'
                    }
                }
            }           
        }
    });
```

This would be a flexible way to keep the current API but add a single 'has' (and it's counter hasOptionally) which now looks into the object properties. Using this method would allow us to keep embedding has, for validating an object inside an object. It wouldn't matter how many levels deep because as long as the schema 'has' it will look below.

Obviously 'has' would only work for Object or plainObject types.

I added 'optionallyHas' incase we don't care whether the object actually has this or not, but perhaps we want to check it if it does.

**Comment by mvhenten** [comment]
Actually, after giving this a bit of thought on my way to work, I figured that two lines of code could implement your feature. ( together with 53 lines of test ).

Still, that won't nest error messages.

Could this d7277e477a78c do the trick? ( don't mind the whitespace changes, js-beatify updated )

**Comment by hongkongkiwi** [comment]
Not nesting error messages is fine, in my case it just throws a wobbly saying the data is invalid, it doesn't go into specifics. I had a look at the change, on paper it looks good (and simple keeping the same protocal).

Only thing that popped into mind is what if you actually had a field named 'optional'... or 'isa' it might get slightly confused. This wouldn't affect me, but I wonder what would happen.

I'll give it a test tomorrow and let you know.

**Comment by givankin** [comment]
@hongkongkiwi have you checked this? =)
@mvhenten this sounds like a really useful feature. What stops you from merging it?

**Comment by mvhenten** [comment]
@abbakym I forgot about it :)

I've merge the issue to master and published an update to npm. Thanks for the headsup.
