### ISSUE TITLE
Support underscore.js

### ISSUE THREAD

**Issue by givankin** [mvhenten/validate-arguments-js#2]
I'd like to use `validate-arguments` in my browser app where I already have underscore, however, it misses the `isPlainObject` method.
It can be easily simulated using other underscore's methods. Would you mind a pull request on this?

**Comment by mvhenten** [comment]
Of course, let me have a look. I perefer lodash over underscore for serverside development, but maybe we can cobble something up.

**Comment by mvhenten** [comment]
no worries

I can hand-pick merge if you like but a pull is more "social" ;-)
